### ISSUE TITLE
不能映射html文件

### ISSUE THREAD

**Issue by xjl456852** [annnhan/ReRes#20]
如果访问的地址是 xxx.com/test.html, 映射本地文件时,映射的e:/test/test.html, 但是访问时,地址了就会出现:data:text/html;charset=utf-8, 后面是是html文件内容, 页面的地址就不正确了, 页面中的form表单无法提交.
请问这怎么解决?

**Comment by annnhan** [comment]
暂时不支持 html 映射

**Comment by plh97** [comment]
会网络协议的前端er 真的不得了咯
